name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write # Needed for creating releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Build Binaries
        run: |
          # Create dist directory
          mkdir -p dist

          # Build for different OS/ARCH combinations
          GOOS=linux GOARCH=amd64 go build -o dist/sai-linux-amd64 ./src/cmd/sai
          GOOS=linux GOARCH=arm64 go build -o dist/sai-linux-arm64 ./src/cmd/sai
          GOOS=darwin GOARCH=amd64 go build -o dist/sai-darwin-amd64 ./src/cmd/sai
          GOOS=darwin GOARCH=arm64 go build -o dist/sai-darwin-arm64 ./src/cmd/sai
          GOOS=windows GOARCH=amd64 go build -o dist/sai-windows-amd64.exe ./src/cmd/sai
          GOOS=windows GOARCH=arm64 go build -o dist/sai-windows-arm64.exe ./src/cmd/sai

          # Create checksums
          cd dist
          sha256sum * > checksums.txt
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/sai-linux-amd64
            dist/sai-linux-arm64
            dist/sai-darwin-amd64
            dist/sai-darwin-arm64
            dist/sai-windows-amd64.exe
            dist/sai-windows-arm64.exe
            dist/checksums.txt
          generate_release_notes: true
          draft: false
          prerelease: false 