name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write # Needed for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_name: sai-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            binary_name: sai-linux-arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary_name: sai-darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            binary_name: sai-darwin-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary_name: sai-windows-amd64.exe
          - os: windows-latest
            goos: windows
            goarch: arm64
            binary_name: sai-windows-arm64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.binary_name }} ./src/cmd/sai

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/${{ matrix.binary_name }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binary-*
          path: dist

      - name: Create Checksums
        run: |
          cd dist
          sha256sum * > checksums.txt
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/sai-linux-amd64
            dist/sai-linux-arm64
            dist/sai-darwin-amd64
            dist/sai-darwin-arm64
            dist/sai-windows-amd64.exe
            dist/sai-windows-arm64.exe
            dist/checksums.txt
          generate_release_notes: true
          draft: false
          prerelease: false 